# Generated by Django 5.0.13 on 2025-06-14 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Axis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short code for the axis (e.g., 'PDCT').", max_length=4, unique=True)),
                ('name', models.CharField(help_text="Full name of the axis (e.g., 'Planning vs Improvising').", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description for the axis.')),
                ('work_style', models.TextField(blank=True)),
                ('work_condition', models.TextField(blank=True)),
                ('work_develop', models.TextField(blank=True)),
                ('work_communication', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The text of the question.', max_length=255)),
                ('option_a', models.CharField(help_text='Text for option A.', max_length=100)),
                ('option_a_value', models.CharField(help_text="Value associated with option A (e.g., 'P').", max_length=1)),
                ('option_b', models.CharField(help_text='Text for option B.', max_length=100)),
                ('option_b_value', models.CharField(help_text="Value associated with option B (e.g., 'I').", max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(blank=True, help_text='Email address of the user who took the test.', max_length=254, null=True)),
                ('responses_json', models.JSONField(help_text='JSON string of raw responses {question_id: value}.')),
                ('scores_json', models.JSONField(blank=True, help_text="JSON string of calculated axis scores {side_value: score}. e.g., { 'P': 7, 'I': 3, ... }", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the result was created.')),
                ('newsletter_consent', models.BooleanField(default=False, help_text='Indicates if the user consented to receive the newsletter.')),
                ('final_type_axis', models.ForeignKey(help_text='The Axis model representing the final personality type.', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='diagnosis.axis')),
            ],
        ),
    ]
